apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s2s-model-cache-pvc
  namespace: maas
spec:
  storageClassName: openebs-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi